### ISSUE TITLE
Bun install segfault in Docker

### ISSUE THREAD

**Issue by Zananok** [vueuse/vue-demi#259]
### What steps can reproduce the bug?

1. Locally on wsl (`PRETTY_NAME="Debian GNU/Linux 12 (bookworm)"`) run: `bunx nuxi init my-nuxt-app` (with bun `1.1.0+5903a6141`) to generate a clean Nuxt app (according to https://bun.sh/guides/ecosystem/nuxt)

2. Rsync to remote vm (also `PRETTY_NAME="Debian GNU/Linux 12 (bookworm)"`)
3. Remove node_modules folder (in the remote)
4. Add the folder of the project as a mapped volume (so, not copying it into the docker, just mapping it from the host) in docker-compose.yml:
```
version "3.8":
...
    image: oven/bun
    ulimits:
      rtprio: 95
      memlock: -1
    volumes:
      - '/apps/${containerName}/data-root/nuxt-dev:/app:z'
```
5. Either from entrypoint or from inside the docker in the workdir /app: `bun --revision && bun install && bun dev`
NB: error occurs on bun install. 

Result:

> 1.1.0+5903a6141
> 2024-04-04T09:00:16.627756172Z bun install v1.1.0 (5903a614)
> 2024-04-04T09:00:33.889355055Z error: postinstall script from "vue-demi" terminated by SIGSEGV (Address boundary error)
> 2024-04-04T09:00:40.747806045Z Segmentation fault (core dumped)

Running bun install and bun dev locally on wsl works.

A more detailed description of the issue can be found here: https://github.com/oven-sh/bun/issues/9924

I am unsure where the problem lies, if with bun or with vue-demi, so I have cross-posted.
