### ISSUE TITLE
Update readme instructions for packages

### ISSUE THREAD

**Issue by dobromir-hristov** [vueuse/vue-demi#37]
I think the Usage section in the readme should be updated.

<img width="946" alt="image" src="https://user-images.githubusercontent.com/9863944/107140523-4827a500-692b-11eb-98d3-5377a371f53a.png">

With npm7, peerDependencies are being installed automatically, and having it like that, causes issues with installations. At Vuelidate we had this issue, until I actually went in, and copied what I saw from Vueuse. Basically removing the peerDeps altogether :D 

I am not sure if that is the right thing to do though :/ Seems to work for Vueuse/core.

**Comment by antfu** [comment]
We have a few discussions (#7 #9 #15) about this and `peerDependencies` seem to be required by yarn2. What's the problem you are running into with npm v7?

**Comment by AMontagu** [comment]
I had the same issue with npm 7. 

# FIX

```
"dependencies": {
  "vue-demi": "^0.6.2",
},
"peerDependencies": {
  "vue": "^2.6.0 || >=3.0.0-rc.0",
  "@vue/composition-api": "^1.0.0-rc.2"
},
"peerDependenciesMeta": {
  "@vue/composition-api": {
    "optional": true
  }
},
"devDependencies": {
  "vue": "^3.0.0"
},
```


## Info on error

Docker image: circleci/node:latest
command: npm install

output:
```
#!/bin/bash -eo pipefail
npm install
[..................] - idealTree:project: sill idealTree buildDeps[[K..................] - idealTree:project: sill idealTree buildDeps[[K..................] - idealTree:project: sill idealTree buildDeps[[K..................] | idealTree:project: sill idealTree buildDepsnpm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: vue-datatable-url-sync@0.1.0
npm ERR! Found: vue@3.0.6
npm ERR! node_modules/vue
npm ERR!   dev vue@"^3.0.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer vue@">= 2.5 < 3" from @vue/composition-api@1.0.0-rc.2
npm ERR! node_modules/@vue/composition-api
npm ERR!   peer @vue/composition-api@"^1.0.0-beta.12" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /home/circleci/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/circleci/.npm/_logs/2021-02-26T17_05_53_678Z-debug.log


Exited with code exit status 1
CircleCI received exit code 1
```

The circle ci file:
```
version: 2
jobs:
  test:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      # TODO

  release:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run: npm install
      - run: npm run build
      - run: npx semantic-release

workflows:
  version: 2
  test_and_release:
    # Run the test jobs first, then the release only when all the test jobs are successful
    jobs:
      - test
      - release:
          requires:
            - test
```
